Repository SocexSolutions/agenda-v2, pull requests merged in 2022-01, with the labels that each got.

#112 Th zb do/meeting submit
  api/lib/controllers/health.js
  api/lib/controllers/meeting.js
  api/lib/controllers/participant.js
  api/lib/controllers/topic.js
  api/lib/index.js
  api/lib/models/meeting.js
  api/lib/models/participant.js
  api/lib/models/topic.js
  api/lib/models/user.js
  api/lib/routes/health.js
  api/lib/routes/participant.js
  api/lib/routes/sendGrid.js
  api/lib/routes/topic.js
  api/lib/routes/user.js
  api/lib/sendGrid.js
  api/lib/sendGrid/emailTemplates/templates.js
  api/lib/sendGrid/sendGrid.js
  api/lib/utils/jwt.js
  api/lib/utils/password.js
  api/test/tests/controllers/health.js
  api/test/tests/controllers/meeting.js
  api/test/utils/api.js
  api/test/utils/client.js
  api/test/utils/http.js
  www/components/AgendaIcon.js
  www/components/Drawer.js
  www/components/DropDown.js
  www/components/Inbox.js
  www/components/Input.js
  www/components/LoadingIcon.js
  www/components/MailBox.js
  www/components/MeetingNameDate.js
  www/components/MeetingParticipants.js
  www/components/Nav.js
  www/components/Notification.js
  www/pages/index.js
  www/pages/login.js
  www/pages/meeting.js
  www/pages/messageExample.js
  www/pages/register.js
  www/pages/user/[id]/index.js
  www/pages/userPage.js
  www/store/features/meetings/meetingSlice.js
  www/store/rootReducer.js
  www/store/store.js
  www/styles/Drawer.module.css
  www/styles/MeetingPage.module.css
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix, hacktober-fest, dependencies, You've not enough minerals., You must construct additional pylons., We are under attack!

#113 changed drawer arrow look
  www/components/Drawer.js
  www/styles/Drawer.module.css
Labels: We are under attack!

#139 Added meeting inbox page that currently gets owned meetings and displ…
  .eslintrc
  api/lib/controllers/participant.js
  api/lib/controllers/user.js
  api/lib/db/index.js
  api/lib/routes/participant.js
  api/lib/routes/user.js
  api/scripts/autoPopulate.js
  api/test/tests/controllers/participant.js
  www/components/DropDown.js
  www/components/Inbox.js
  www/pages/login.js
  www/pages/meeting/[id]/index.js
  www/pages/user/[id]/index.js
  www/store/features/meetings/meetingSlice.js
  www/store/features/user/userSlice.js
  www/styles/Inbox.module.css
Labels: bug, help wanted, wontfix, hacktober-fest
